enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "crimera ReVanced"
arch = "arm64-v8a"
excluded-patches = "'Disable chirp font' 'Remove view count' 'Hide bookmark icon in timeline' 'Hide Live Threads' 'Hide nudge button' 'Enable force HD videos' 'Hide Banner' 'Hide followed by context' 'Hide hidden replies' 'Hide promote button' 'Hide Community Notes' 'Enable debug menu for posts' 'Round off numbers' 'Remove "Who to follow" Banner' 'Remove "Communities to join" Banner' 'Remove "Pinned posts by followers" Banner' 'Remove Detailed posts' 'Remove videos for you' 'Remove main event' 'Remove message prompts Banner' 'Remove superhero event' 'Dynamic color'"
